### ISSUE TITLE
Advanced search hide broken option

### ISSUE THREAD

**Issue by andyklimczak** [segler-alex/radiobrowser-api-rust#100]
Advanced search endpoint (`http://de1.api.radio-browser.info/json/stations/search`) does not utilize a `hideBroken` param, unlike the List of radio stations endpoint (`http://de1.api.radio-browser.info/{format}/stations/byuuid/{searchterm}`).

Was wondering if `hideBroken` param could be added to the advanced search endpoint to match polarity

Thanks!

**Comment by segler-alex** [comment]
it was already the case, but not documented. i added it to the documentation in version 0.7.12

**Comment by andyklimczak** [comment]
Thanks!
