### ISSUE TITLE
Support offset & limit parameters for /stations/lastchange

### ISSUE THREAD

**Issue by onny** [segler-alex/radiobrowser-api-rust#103]
Hey,
to be in consistency with the other API endpoints, it would be nice to also have parameters "offset" and "limit" for ``/stations/lastchange``.
Currently http://de1.api.radio-browser.info/json/stations/lastchange?offset=1&limit=20 doesn't show anything. A limit is supported with http://de1.api.radio-browser.info/json/stations/lastchange/5 but then "offset" is not working too :,(

Best regards
Jonas

**Comment by segler-alex** [comment]
if you need it for paging, i would not use it this way, because it is possible to change without you noticing.
it is basically SQL: ORDER BY ChangeDateTime DESC LIMIT number
if someone adds a stream while you are browsing, you will a result that is not consistent.
what do you think?

**Comment by segler-alex** [comment]
fixed in 0.7.12
