### ISSUE TITLE
Not all stations support https connection and no indication which works and which doesn't

### ISSUE THREAD

**Issue by 432player** [segler-alex/radiobrowser-api-rust#106]
We need to use an **https** connection for our js client app which streams from radio-browser.
So we override each **http** call for the url of a station to be https and try to play the edited url with a simple **js fetch** command.
Some stations work (we get the stream and it plays) and some dont, we couldnt find a way to filter out those stations that could not be reached with a secure connection and remove them from our list automatically.
What are we missing?

**Comment by segler-alex** [comment]
you cannot just change http and https for streams!
radio-browser is just an index like google
if a stream does not support one or the other radio-browser cannot help you with that.
