### ISSUE TITLE
Can you provide installation without compose cluster?

### ISSUE THREAD

**Issue by denisgolius** [segler-alex/radiobrowser-api-rust#107]
Can you provide installation without compose cluster or add something like k8s manifest to run in in kubernetes?

**Comment by segler-alex** [comment]
i added a helm chart for k8s at https://gitlab.com/radiobrowser/helm-charts

**Comment by denisgolius** [comment]
> i added a helm chart for k8s at https://gitlab.com/radiobrowser/helm-charts

This repository is a private.

**Comment by segler-alex** [comment]
i made it public, sorry. i thought it is public by default. please try again
