### ISSUE TITLE
BBC Radio stations does not work

### ISSUE THREAD

**Issue by kuba14** [segler-alex/radiobrowser-api-rust#110]
All the BBC radio stations changed their stream addresses. They do not work on RadioBrowser for a few days. Could you please update them? Those streams are important and widely used. 

[All the new streams of these radio stations can be found here.](https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3)

**Comment by broughy** [comment]
Agree these are widely used and need updating please :)

**Comment by marekfri** [comment]
Totally agree, those ones are important to us too.

**Comment by segler-alex** [comment]
bbc has been added by someone again, this is self service. if you need streams please go to 
https://www.radio-browser.info/#!/add
