### ISSUE TITLE
Servers are not sync

### ISSUE THREAD

**Issue by haecker-felix** [segler-alex/radiobrowser-api-rust#111]
I select the API servers in Shortwave at random. I noticed that the data is not consistent. For example a station with the same GUID is having different votes count on different servers:

`DE1` Server: 169 Votes (https://de1.api.radio-browser.info./json/stations/byuuid/9631dea0-0601-11e8-ae97-52543be04c81)

`NL1` Server: 16759 Votes(https://nl1.api.radio-browser.info./json/stations/byuuid/9631dea0-0601-11e8-ae97-52543be04c81)

I think the servers are supposed to sync, so they're having all the same data?

**Comment by segler-alex** [comment]
thank you, i noticed sync is not perfectly working, but did not have time yet to fix it.
there are even some streams that are not there on all servers. i hope i can fix it the following week. do not have a clue yet why votes are not in sync.
