### ISSUE TITLE
radiobrowser should follow redirects

### ISSUE THREAD

**Issue by 1358** [segler-alex/radiobrowser-api-rust#112]
Some "load balancer" redirect not only via 301/302 but also with 303 to the actual stream url. At the moment RadioBrowser does not follor 303 redirects and marks these stations as broken.

example: http://www.radio-browser.info/gui/#/edit/96876

**Comment by segler-alex** [comment]
i checked it, the api does always follow links on all codes from 300 to 399 IF there is a Location header so that it actually knows where to go.
