### ISSUE TITLE
Can we have servers location field please? (/json/servers et al)

### ISSUE THREAD

**Issue by s-n-g** [segler-alex/radiobrowser-api-rust#113]
Hi there @segler-alex 

I am back on working on ```radiobrowser``` support for ```pyradio``` after such a long long time...
So this is where [I am at the moment](https://forum.maboxlinux.org/uploads/default/optimized/1X/fb2a20f918f499a2334a0e126639c3d4c464bd2d_2_1035x646.png
) (just showing 100 top votted stations, no search function yet...)

So, here's the thing: I would like to make it possible for the user to select a specific server, so I would like to present to him the server location instead of / along with the url. Is it too much trouble to ask you to add a "**location**" field on these?

Thanks
S.

BTW, I have noticed server sync is a bit off. searching fot "big band" tag (hidebroken=True) I get "The UK 1940s Radio Station"  [http://149.255.59.162:8062/stream](http://149.255.59.162:8062/stream) (top votted) station on ```fr1``` and ```nl1``` servers, but it's not there on ```de1```. The station is broken (does not play).

**Comment by segler-alex** [comment]
yes, i will add 2 fields at /json/config endpoint

* Freeform location string for this server
  server-location = "Datacenter 2 in coolstreet"
* 2 letter countrycode to locate this server
  server-country-code = "DE"

**Comment by segler-alex** [comment]
will be there in 0.7.10
