### ISSUE TITLE
Are stations with the same URL the same station?

### ISSUE THREAD

**Issue by micrococo** [segler-alex/radiobrowser-api-rust#114]
There are many stations with the same URL (2223 URLs are shared by two or more stations). I want to remove the duplicated streams if they really are the same for a personal project.

**Comment by segler-alex** [comment]
i am currently working on an automated way of removing duplicates from the database.

**Comment by micrococo** [comment]
It seems there are no duplicates anymore. Can I close the issue or is there something to be done?

**Comment by segler-alex** [comment]
it still has bugs but much better than before
