### ISSUE TITLE
Any way to discover stations by country code or states?

### ISSUE THREAD

**Issue by deep5050** [segler-alex/radiobrowser-api-rust#115]
I have made an app (radioactive) using pyradios module. I don't know whether this API does not support this or the python wrapper did not implement this! 

I can see people are having trouble finding the right station (often searching station with their country name). I want to add an option to discover nearby stations. Is it anyhow possible?

**Comment by segler-alex** [comment]
i tried it out. you can use the advanced search in pyradios:
```python
from pyradios import RadioBrowser
rb = RadioBrowser()
rb.search(countrycode="AT",limit=3)
```
here are the docs for supported parameters
https://de1.api.radio-browser.info/#Advanced_station_search

**Comment by segler-alex** [comment]
how to get help for pyradios
```python
from pyradios import RadioBrowser
help(RadioBrowser)
```
