### ISSUE TITLE
Missing FM [Malaysia]

### ISSUE THREAD

**Issue by jachk96** [segler-alex/radiobrowser-api-rust#118]
Is anyone able to find the stream URL for these two FM? Country: Malaysia

1. https://www.flyfm.com.my/
2. https://goxuan.my/

I went into its page source and inspect but nothing get. 
Is any professional guidance able to guide me this newbie here on how to get the stream URL? Thank you.

**Comment by segler-alex** [comment]
this database is self-service. please add streams at
https://www.radio-browser.info/add

**Comment by jachk96** [comment]
> this database is self-service. please add streams at https://www.radio-browser.info/add

I know it is self service. 
But what I mean is how to get that 2 radio stream URL? Any guidance? 
Thanks.
