### ISSUE TITLE
Where can I add a term in Advanced station search

### ISSUE THREAD

**Issue by shinokada** [segler-alex/radiobrowser-api-rust#120]
[Advanced station search](https://de1.api.radio-browser.info/#Advanced_station_search) says:

A list of radio stations that match the search. It will search for the station whose attribute contains the search term. 
And the example is http://de1.api.radio-browser.info/json/stations/search.

Where can I add a search term? I tried http://de1.api.radio-browser.info/json/stations/search/jazz but no results returned.

The same thing for Search radio stations by UUID and Search radio stations by URL. Where can I add a search term?

**Comment by s-n-g** [comment]
At the begining pf the code:

> Please note that all the parameters listed below can be added by using an HTTP POST request with the encoding "x-www-form-urlencoded" instead of GET request, and they can also be sent with encoding "application/json" used by Angular.js, for example.

**Comment by shinokada** [comment]
Thanks. This works.

```
curl -X POST -d 'name=jazz' -d 'countrycode=AU' http://91.132.145.114/json/stations/search
```
