### ISSUE TITLE
How to download radio stations in a playlist?

### ISSUE THREAD

**Issue by szedar14** [segler-alex/radiobrowser-api-rust#123]
On the page [https://www.radio-browser.info/#/](url), after selecting the country, PL shows 10 radio stations, of which there are many more than 700, but when I download a playlist, I only get 10 radio stations. My question is how should I download all radio stations from a given country.

**Comment by nepodev** [comment]
`http://all.api.radio-browser.info/m3u/stations/search?countrycode=PL`

**Comment by szedar14** [comment]
Thanks @nepodev 
it's a pity that you need to have some knowledge on how to get such a list. It will not be possible for an ordinary person.

**Comment by nepodev** [comment]
I see. In this case your request belongs to the frontend https://github.com/segler-alex/radiobrowser-web-angular
This repository is for the API.

**Comment by big610** [comment]
It would be nice to have an option for the ability to change the view, to view all, like it was before. This encourages the ability to Add, check & view Favicons, URL addresses, and stations not in the data.
