### ISSUE TITLE
Is server down?

### ISSUE THREAD

**Issue by NomadicWarrior** [segler-alex/radiobrowser-api-rust#124]
From yesterday I can't load any stations. Error message: 
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.41 (Ubuntu) Server at de1.api.radio-browser.info Port 443

**Comment by junaru** [comment]
https://www.radio-browser.info  also returns no results or statistics.

**Comment by s-n-g** [comment]
It seems that ```de1.api.radio-browser.info``` is down; ```fr1.api.radio-browser.info``` and ```nl1.api.radio-browser.info``` are still ok
