### ISSUE TITLE
Update for Jazz FM UK

### ISSUE THREAD

**Issue by MightyBob** [segler-alex/radiobrowser-api-rust#126]
Radio station update request:
name : Jazz FM UK
stationuuid : 072ca45f-9d0f-4c54-878b-fbfd45220843

--> update with this:
favicon: https://media.bauerradio.com/image/upload/c_crop,g_custom/v1609760854/brand_manager/stations/scdlfxjatzxd6iesdonp.png

**Comment by segler-alex** [comment]
only the streaming station itsself may update streams
