### ISSUE TITLE
Load stations page by page. Limit and offset.

### ISSUE THREAD

**Issue by NomadicWarrior** [segler-alex/radiobrowser-api-rust#127]
Is it possible to have a limit of loading stations for example? At the first launch load, 20 stations and the user scrolls up, load another 20 stations. I found some API of your in Rapid API. It gives limit and offset but need api key to use it. https://rapidapi.com/phranck/api/radio-browser/

**Comment by segler-alex** [comment]
you could just use the real api, without rapidapi at 
https://api.radio-browser.info/
