### ISSUE TITLE
invalid JSON on /json/url/[radioId]

### ISSUE THREAD

**Issue by klues** [segler-alex/radiobrowser-api-rust#13]
E.g. this call:
http://www.radio-browser.info/webservice/json/url/104423

returns invalid JSON:
`[{"ok":"true","message":"retrieved station url successfully","id":"104423","name":"WNIS "News Talk 790" Norfolk, VA","url":"http://20603.live.streamtheworld.com:3690/WNISAMAAC_SC"}]`

The double quotes in field `name` are not escaped.

**Comment by segler-alex** [comment]
fixed, thank you for reporting

**Comment by klues** [comment]
great, thanks! 👍
