### ISSUE TITLE
"Bayern 3" end streaming at the end of this year

### ISSUE THREAD

**Issue by msfox** [segler-alex/radiobrowser-api-rust#131]
I hear Bayern 3 via Android App "Radiodroid". Radiodroid get the URL from https://www.radio-browser.info. In this stream notify, that end streaming at the end of this year.
The Kodi addon "radio.de" get the streams from radio.de. There the Bayern 3 - Stream is "https://dispatcher.rndfnk.com/br/br3/live/aac/low?aggregator=radio-de".
Maybe, anyone can add this stream to radio-browser.info https://www.radio-browser.info/history/9640db63-0601-11e8-ae97-52543be04c81.

Best Regards
ms

**Comment by segler-alex** [comment]
broken streams will get removed from the database automatically
please just readd the new stream
