### ISSUE TITLE
Question: is stream-meta version2 supported?

### ISSUE THREAD

**Issue by boyska** [segler-alex/radiobrowser-api-rust#133]
Hello, and thanks for the project!

I'd like to know if https://www.stream-meta.info/version_2.html is already supported: that is, if I have a `/streaminfo.json` in my website, and this website is referenced by `icy-url`, should those data be fetched and available in `radio-browser.info`?

I don't see this happening, but maybe I'm just doing it wrong.

Thanks!

**Comment by segler-alex** [comment]
/streaminfo.json is not yet supported only the first part of version_2 which is documented at
https://www.radio-browser.info/owners

please provide your stream url, then i will investigate further and will implement this behaviour.

**Comment by boyska** [comment]
Here it is:
 - https://www.radio-browser.info/history/ce63c422-128b-4f5b-a1e9-d6ee49f2b9a3
 - http://s.streampunk.cc/ondarossa.ogg
 - http://www.ondarossa.info/
 - http://www.ondarossa.info/streaminfo.json

thanks!

**Comment by boyska** [comment]
Hello! is there any news about it? Is there any wayy I can help?

**Comment by PaulWebster** [comment]
I thought I would take a look at implementing streaminfo.json support ... but I struggled to work out where it should go in the code.
Is check.rs the module I should be looking at?
