### ISSUE TITLE
Feature Request: add http stream url to stations and let that be a search parameter

### ISSUE THREAD

**Issue by Canuma** [segler-alex/radiobrowser-api-rust#135]
I guess this request is not very reasonable, yet I 'd like to propose that stations get another field for http urls, if they have any. 
I ask, because I am currently toying arround with [YCast](https://github.com/milaq/YCast). Unfortunately, most (all?) AVRs can't handle https requests. Ycast works around that limitation by replacing all https requests with http. This works to some extend, but obviously it also fails from time to time, because either the station does only https, or and that is why I am requesting this, they have a different http url.
For existing stations, or stations where no http was given, maybe radiobrowser could check if there exists a non secure url based on the secured one. I'd check it myself in ycast, but i can not imagine a way to make those checks fast enough, if I had to check every station.
And yeah, I'd totally understand if that is too much to ask, as it'd be just a legacy feature anyway.

**Comment by segler-alex** [comment]
this is a feature that is actually on my todo list.
i want to test every stream for http and https support and then add another selector in the search endpoint
to get only http, only https or both streams as result

BUT it will take time until i get to it

**Comment by Canuma** [comment]
That's good to hear. Thanks for this great project.

**Comment by segler-alex** [comment]
https://gitlab.com/radiobrowser/radiobrowser-web-angular/-/issues/8
