### ISSUE TITLE
Problem adding some stations manually

### ISSUE THREAD

**Issue by huhas12** [segler-alex/radiobrowser-api-rust#138]
Is there any guide how to add stations without a resolved url ?

I would like for example to manually add this station http://www.athensdeejay.gr/ or this one http://live24.gr/radio/atlantisfm.jsp , the problem is that the streaming url e.g. for the second is http://85.10.206.222:8012/stream but dosen't work... As long as the first I cannot find it! 

Any ideas?

**Comment by drspy00** [comment]
I am having the same issue with many stations. Literally anything I want to listen to is not able to be added, but plays fine in the browser, and any other app. :(

**Comment by segler-alex** [comment]
https://gitlab.com/radiobrowser/radiobrowser-web-angular/-/issues/8
