### ISSUE TITLE
Radio Browser Amazon Alexa Skill

### ISSUE THREAD

**Issue by MichaelDworkin** [segler-alex/radiobrowser-api-rust#140]
Hello Alex,
please add my project to app list.
Alexa Skill Radio Browser
my skill uses your database to play rado with on amazon alexa devices. Users can create their own favorites list and then call them by number. This solves the problem that Alexa does not understand foreign names.
https://esp8266-server.de/alexa/RadioBrowser/en/
I know writing this here is not quite correct.
i tried to contact you via mail, but you don't answer.

**Comment by segler-alex** [comment]
thank you a lot for you work!
i added the link to the list.
the code for the website is on
https://gitlab.com/radiobrowser/radiobrowser-web-angular
