### ISSUE TITLE
[Feature request] Circumvent geoblocked streams

### ISSUE THREAD

**Issue by CountOmega** [segler-alex/radiobrowser-api-rust#141]
It would be nice if radio-browser supported un-blocking of certain streams. E.g. afaik iheartradio are blocked outside of the United States and Canada. Since radio-browsers API servers are based in Europe I can't stream [The Bear](https://www.iheartradio.ca/100-3-the-bear/ ) for example. It works fine with a VPN though.

**Comment by Dealman** [comment]
This API just serves as a means to discover and search for stations using various credentials. The actual origin of these streams remain unchanged.

The API itself is hosted on European servers, this doesn't necessarily mean the radios are also being broadcast from Europe.

A potential way to bypass this would be to use Amazon's AWS services to host a free tier virtual server in the US and then you could proxy the station using PHP or some other backend language.

**Comment by segler-alex** [comment]
bypassing geoblocking is out of scope for this project.
please use VPN for that.
this project serves as a place to discover streams much like a "searching machine"
