### ISSUE TITLE
Getting Stations by UUID Array - Not Working

### ISSUE THREAD

**Issue by Dealman** [segler-alex/radiobrowser-api-rust#142]
It works if you provide the API with 1 UUID, multiple when separated by comma will only return an empty JSON array.

Tested URLs:
`https://fr1.api.radio-browser.info/json/stations/byuuid/beb65192-9301-11e8-a767-52543be04c81,16a73a57-5dba-11e8-b0ce-52543be04c81`
`https://fr1.api.radio-browser.info/json/stations/byuuids/beb65192-9301-11e8-a767-52543be04c81,16a73a57-5dba-11e8-b0ce-52543be04c81`
`https://fr1.api.radio-browser.info/json/stations/byuuid/uuids=beb65192-9301-11e8-a767-52543be04c81,16a73a57-5dba-11e8-b0ce-52543be04c81`
`https://fr1.api.radio-browser.info/json/stations/byuuid&uuids=beb65192-9301-11e8-a767-52543be04c81,16a73a57-5dba-11e8-b0ce-52543be04c81`

**Comment by Dealman** [comment]
Correction, it does work. The documentation confused me. Correct syntax is;
`https://de1.api.radio-browser.info/json/stations/byuuid?uuids=9642ad8b-0601-11e8-ae97-52543be04c81,16a73a57-5dba-11e8-b0ce-52543be04c81`

I had a feeling it was me doing something wrong since everything else has worked flawlessly 😆

**Comment by terenc3** [comment]
I made the same mistake. Thanks for providing the solution
