### ISSUE TITLE
UUID format uppercase/lowercase

### ISSUE THREAD

**Issue by NerfBro** [segler-alex/radiobrowser-api-rust#147]
I've noticed that the following call will fail if the UUIDs are in capitals. It took me many hours to figure this out...
https://all.api.radio-browser.info/json/stations/byuuid?uuids=d873afb3-277f-4d42-9b36-ced320409734,9615d27a-0601-11e8-ae97-52543be04c81

I know the standard is that they be lowercase, but to make the API more compatible with the most frameworks could this call be made non case sensitive?

**Comment by segler-alex** [comment]
i will do a conversion to a default lower case on this input in the next version
