### ISSUE TITLE
Multiple steams per station 

### ISSUE THREAD

**Issue by NerfBro** [segler-alex/radiobrowser-api-rust#149]
Some radio stations have multiple streams available to them. What is the best practice way of putting them all together under a single name? Is there any way to collapse them together into a single array of streams for that station? Is there a clever search I could do on a single parameter to isolate them? Is there something simple and obvious that I’ve missed?

**Comment by segler-alex** [comment]
Currently, there is no way to merge streams.
Every stream stands for its own.
This was a design decision and would need a major rewrite to change.
For the time being, I do not have time to do such an undertaking. It would also change how stations would be added to the database, it would need editing functionality for streams (sometimes single streams change to a station but others don't). Sometimes new ones have to be added to a "stream group" of a station. 
This would also change the API as a whole to embrace the idea fully.

If you have any ideas on how to do this technically without a rewrite, feel free to reply.

**Comment by NerfBro** [comment]
To minimise disruption and redesign I would propose that streams for the same radio station share the same name. I think this is already possible because the IDs for each stream are already unique. It’s just needs to be made the best practice when adding new stations. 

In the meantime I suggest grouping them together using the homepage/domain url of the station. Are you able to tell me if I can do a search on homepage URLs?

Many thanks.
