### ISSUE TITLE
Tens of thousands of unnecessary characters in some streaming links

### ISSUE THREAD

**Issue by GHbasicuser** [segler-alex/radiobrowser-api-rust#154]
Hi,

I noticed that there were many radio station links in the database that contained more than 14,000 totally useless (extra) characters. (like this one "Tick Tock Radio - 1950" - https://www.radio-browser.info/history/cde988ac-9376-41c7-a29c-ae779cbb5830 - 14.000 "O" and a F* y.. at the end)

Most seem to be "Tick Tock" (IceCast Audio) radio stations. Wouldn't there be a way to prevent this and clean up the base?

Thank you, Good continuation !

**Comment by JazzfanRS** [comment]
Possible new issue? After 6 days this broken link is still in database? (I submitted a new station (info) from Tick Tock website, so we'll see.

**Comment by GHbasicuser** [comment]
This link isn't broken, it contains thousands of extra characters (totally useless) but it's functional. 😐

**Comment by JazzfanRS** [comment]
I stand corrected. I jumped to that conclusion because the link doesn't present itself before conversion to the .rsd format we need for RadioSure. I'll stop fussing at radio-browser.. :)

**Comment by JazzfanRS** [comment]
With URL links varying in length perhaps @segler-alex could be limit the length.  I've rarely seen one longer then 30 characters. 

The overall nature of the input fields should have some restraint. Tags in particular. Shouldn't that Genre? It is what the example tags reveal. Also the number of allowed 'tags' is problematic for anyone using the backups in their application.

**Comment by Explosion-Scratch** [comment]
What about using a URL shortener for `url_resolved` if it is over a certain length? I know that `is.gd` has a public no limits no auth api for this

**Comment by JazzfanRS** [comment]
All wonderful ideas. But I think this was misunderstood. The problem I had with long urls was how they appear within the radiosure app. Normally not a problem. It's when actually viewed that it is problematic. But mostly it's a non issue. And really unimportant. 

Retaining them is a personal choice. I simply remove them from any updates I download. But lately I only use my own database of favorites. As I no longer channel surf.

**Comment by JazzfanRS** [comment]
It apparently isn't important to the author at all if the link works anyway. And is good enough.

**Comment by JazzfanRS** [comment]
The problem has always been input fields are too loosely controlled, causing the database to be too sloppy for any use other then Station name and working URL streams.

**Comment by JazzfanRS** [comment]
I have simply decided to strip all URL parameters (anything after the question mark) as I have no reason to care to share a referrer links, etc. The point is to listen to internet streaming. Converting the database into a cleaner, tighter format usuable and readable by users who barely know how to turn the computer on.
