### ISSUE TITLE
Where to make suggestions for radio-browser appearance (GUI)?

### ISSUE THREAD

**Issue by JazzfanRS** [segler-alex/radiobrowser-api-rust#161]
The current GUI is cumbersome to use, as it looks to be aimed at cellphone users alone without a different appearance for desktop users.
Is it fair to criticize that the site uses clickcount? I thought the point of the site was a station database, not a popularity contest. Which leads to over zealous submitters adding every possible genre in a tag (incorrectly) and vandalism of rival stations URLS.

I understand the sentiment of anti-Putin graphics used in station logos (URL redirects?) and messages in the URL, but please, this is not the platform for that.

**Comment by ArtyIF** [comment]
https://gitlab.com/radiobrowser/radiobrowser-web-angular

**Comment by JazzfanRS** [comment]
> https://gitlab.com/radiobrowser/radiobrowser-web-angular

My mistake. I am aware of this link, however I don't know anything of programming, just graphic design, and my knowledge of html is limited. I was hoping to offer some suggestions on RBI/search page
