### ISSUE TITLE
Several hundred duplicates in database, and how to deal with them.

### ISSUE THREAD

**Issue by JazzfanRS** [segler-alex/radiobrowser-api-rust#165]
Finding several hundred duplicate listings (based on exact copy of individual lines.) Why aren't they culled before creating the daily .zip?

Separate issue related to duplicate listing: Allow for multiple formats instead of just one per submission. Dozens of stations have Mp3 and AAC. Allow those to be placed in one listing (submission).

**Comment by pvagner** [comment]
I've just submitted a station which has already been added I have just searched wrong. Perhaps when adding stream url which is already in the database, it should refuse to add it again.

**Comment by JazzfanRS** [comment]
To my understanding there was script in place to remove duplicates, but it's been awhile since I looked that closely at the SQL. I just decided to remove them from the download with my own script along with other problems in their database. What format do you use the database in. I have it set up to download daily, delete everything but Name, Country, Language, and Genre, and source URL and format in a tab separated format (plaintext) for use by RadioSure PC app.

**Comment by JazzfanRS** [comment]
Reopened. My understanding is that duplicate entries were being deleted in a timely
