### ISSUE TITLE
Correct favicons are being removed.

### ISSUE THREAD

**Issue by MoiMerino** [segler-alex/radiobrowser-api-rust#168]
Hello Segler Alex,

I have been a big fan of your app for about two years now, ever since I discovered it I have been a great contributor to it, adding a lot of radio stations from my country (Mexico) and even a few other few stations from other countries with all the complete necessary data (name, url, homepage, country subdivision, country, language, tags, geoinfo, etc.). For some time, until today, several of these added radio stations have been losing their favicon, this may have been going on for a couple of months, however recently (approximately two weeks) a large number of stations, no longer We're talking about dozens, if not hundreds of stations have been losing their favicon on the app. What seems strange to me about this is that the links to the favicons are not really incorrect, nor have the files with the logos (favicons) disappeared, I don't know if it is an error on the part of how your database is updated or the one that uses the application, I really don't know anything about programming, I'm just a big fan of Radio Droid and I would like to make the comment and observation that I have noticed, to see the possibility that you can recover this information that is being lost, In the event that it is not possible, perhaps in the future correct the error by which this is happening, thus avoiding the loss of more favicons of the stations. Thank you for your great contribution with this great application for all of us who love radio.

**Comment by dreisafer** [comment]
At my station the favicon was also gone, 2 days later it was suddenly back, only to disappear again 1 day later. Since then it is gone. That is now 1 year ago. Here, however, no one seems to really care anymore.
