### ISSUE TITLE
what happened to issue 49?

### ISSUE THREAD

**Issue by mailinglists35** [segler-alex/radiobrowser-api-rust#174]
[website FAQ](https://www.radio-browser.info/faq) links to https://github.com/segler-alex/radiobrowser-api-rust/issues/49 which github gives 404.

What is the status of updating stations? For example I'd like to add additional streams to one of my favorite stations.

Thanks

**Comment by onny** [comment]
Still a big issue :(

**Comment by bentolor** [comment]
@mailinglists35 no 404 for me (any more). Think you can close your duplicate issue.

**Comment by mailinglists35** [comment]
@bentolor duplicate of what? 

@bentolor at the time of opening this issue, the referenced issue had a privacy setting that would make it inaccessible to public. looks like meanwhile the author has changed it back to public
