### ISSUE TITLE
“Infowars” stations listed as “news”!  This is dangerous⚠️

### ISSUE THREAD

**Issue by bruceleerabbit** [segler-alex/radiobrowser-api-rust#177]
The DB has some of the Alex Jones “Infowars” stations tagged as “news”. This is dangerous and disturbing. This show a source of wild conspiracy theories that are falsely presented as “news”.

To give a concrete example of the beast at hand, Alex Jones told his listeners that Hillary Clinton was running a child sex ring in the basement of a New York pizza parlor. One of his listeners believed the “report”, packed his gun and took to an interstate road trip to attack the place. Full story here:

https://www.rollingstone.com/feature/anatomy-of-a-fake-news-scandal-125877/

Jones’ lawyer told the court Jones is not a journalist and that he is an “entertainer”. That basis got Jones off the hook for pushing misinfo. When www.radio-browser.info tells visitors that Infowars is “news”, it’s dangerous.

IIUC, RB is automated and mechanically trusts a source to properly label its own content. But in this particular case an override is needed. If that’s not feasible, then the record should be excluded from the DB. It should be clear to users that Infowars is *not* factual news. It should be made unmistakably clear that it’s fiction/fantasy.

**Comment by awsms** [comment]
Lmao
