### ISSUE TITLE
BBC is switching to DASH – can Radio Browser / RadioDroid respond?

### ISSUE THREAD

**Issue by sebalis** [segler-alex/radiobrowser-api-rust#181]
Hi,

Some time in mid-2023, all the existing BBC Radio streams will stop working ([see announcement](https://www.bbc.co.uk/sounds/help/questions/recent-changes-to-bbc-sounds/shoutcast-closure)) as the BBC will phase out Shoutcast technology. Only DASH/HLS will be supported and the new stream URLs can be found (see [here](https://github.com/MusicPlayerDaemon/MPD/issues/560#issuecomment) for example). My main use of Radio Browser is to listen to BBC Radio via RadioDroid. I am aware of issue #49 and I am wondering how best to react to that change.

– The community could add new entries for all the new streams (I have edited the existing entries in the past) but it would not be convenient for future users to find a large number of entries, half of which point to streams that are no longer working. Search for BBC on radio-browser.info to see the scale of the problem.

– Given the debate in #49 I wonder if a way could yet be found to change the existing entries, either generally (might @segler-alex adopt the Git approach suggested lately?) or just for the BBC streams, as these are probably quite important entries in the database.

– I don’t even know if RadioDroid could play DASH streams once they are added – can it? As the app does not support adding URLs from a source other than Radio Browser, I don’t know how to test that.

What does @segler-alex think, or does the community have an idea?

**Comment by prodrigestivill** [comment]
Hello @sebalis,

Radio Browser is currently supporting **HLS** with [a lot of stations already present](https://www.radio-browser.info/search?tagList=hls).
As stated in the BBC [announcement](https://www.bbc.co.uk/sounds/help/questions/recent-changes-to-bbc-sounds/shoutcast-closure) you shared, BBC will keep supporting HLS so it should not be an issue for this specific station with Radio Browser.

Another thing would be a feature request to add DASH support, not sure what is the current status nor the actual roadmap.

**Comment by sebalis** [comment]
Thanks for the response. But the other not insignificant question remains open. There are many BBC streams in the database, and these will be popular entries. Are these going to remain as “dead” entries, and will each stream be given a second entry? Those second entries would be hard to distinguish unless some marker is added to the title, which would be inconvenient. I don’t see a good solution unless the existing entries are changed in some way, or deleted.
