### ISSUE TITLE
Vote for station JSON request returns XML response

### ISSUE THREAD

**Issue by wolfmanfp** [segler-alex/radiobrowser-api-rust#19]
Sending a request for example to the URL `https://de2.api.radio-browser.info/json/vote/125` returns this:
`"<result>\n  <status ok=\"true\" message=\"voted for station successfully\"></status></result>"`
instead of a JSON response.

**Comment by segler-alex** [comment]
fixed, will be in version 0.5.1
you can get the version on /json/stats
