### ISSUE TITLE
Radio 32, Stream has changed

### ISSUE THREAD

**Issue by roland68** [segler-alex/radiobrowser-api-rust#192]
For Radio 32 (https://www.radio-browser.info/history/96101926-0601-11e8-ae97-52543be04c81) the stream-URL has changed.
The new value is: https://stream.streambase.ch/radio32/mp3-192/chmedia-today-web
Can you please modify the value in the DB?

**Comment by vdbhb59** [comment]
You can add or update via the website itself. I think.
