### ISSUE TITLE
Services offline

### ISSUE THREAD

**Issue by Suplanus** [segler-alex/radiobrowser-api-rust#207]
https://de1.api.radio-browser.info/
https://fr1.api.radio-browser.info/

---
at1.api.radio-browser.info works. I have to fix the DNS lookup because I am only checking if the server is pinging back... not checking if the service is running 🙈

**Comment by Sanrel** [comment]
https://at1.api.radio-browser.info/    502 Bad Gateway

**Comment by vdbhb59** [comment]
Only fr1 is not working. Rest are working fine. @segler-alex
