### ISSUE TITLE
State and language are reverse

### ISSUE THREAD

**Issue by danielro** [segler-alex/radiobrowser-api-rust#28]
Thank you for your efforts on keeping this project online.

I've found that when querying stations by uuid, state and language values are reverse.

https://de2.api.radio-browser.info/json/stations/byuuid/963f632e-0601-11e8-ae97-52543be04c81

> 
> bitrate: 128
> ​​
> changeuuid: "963f6333-0601-11e8-ae97-52543be04c81"
> ​​
> clickcount: 0
> ​​
> clicktimestamp: ""
> ​​
> clicktrend: 0
> ​​
> codec: "MP3"
> ​​
> country: "United States of America"
> ​​
> countrycode: "US"
> ​​
> favicon: "http://web03.cabeard.k12.in.us/wkpw/Classic%20Hits%20Blue%20Swirl%20512%20x%20512%20px%20red%20&%20yellow.jpg"
> ​​
> hls: 0
> ​​
> homepage: "http://www.wkpwfm.com/"
> ​​
> language: "Indiana"
> ​​
> lastchangetime: "2019-12-12 20:38:59"
> ​​
> lastcheckok: 1
> ​​
> lastcheckoktime: "2020-01-06 23:59:46"
> ​​
> lastchecktime: "2020-01-06 23:59:46"
> ​​
> lastlocalchecktime: ""
> ​​
> name: "WKPW 90.7 \"Classic Hits\" Knightstown, IN"
> ​​
> state: "english"
> ​​
> stationuuid: "963f632e-0601-11e8-ae97-52543be04c81"
> ​​
> tags: "knightstown,classic hits,classic rock,oldies"
> ​​
> url: "http://165.139.147.234:8081/wkpw"
> ​​
> url_resolved: "http://165.139.147.234:8081/wkpw"
> ​​
> votes: 0

language: "Indiana"
state: "english"

**Comment by segler-alex** [comment]
thank you! i found the bug. will be fixed in the next release.
greetings from vienna/austria
