### ISSUE TITLE
remove extra api call for getting real url

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/radiobrowser-api-rust#3]
add resolved_url field to normal station information

**Comment by alivannikov** [comment]
Would be super useful. For example we are currently just filtering out all the playlist type of radio stations, because it is not feasible for us from performance point of view to make additional per-station http requests to resolve playable url.

**Comment by segler-alex** [comment]
added random order to every station search request

**Comment by segler-alex** [comment]
added url_resolved field to results, deprecated /url endpoint
