### ISSUE TITLE
Update a station

### ISSUE THREAD

**Issue by isjsg97** [segler-alex/radiobrowser-api-rust#55]
I added a new radio station, but I was wrong in the url, how can I update it to put the correct one?

**Comment by isjsg97** [comment]
Just in case the update has to be done by some admin, I leave the information here:

stationuuid: e3ea6c86-9909-44e8-af6e-336f25cdf859
current and wrong url: http://icecast-streaming.nice264.com/melodiafmback
CORRECT URL: http://icecast-streaming.nice264.com/melodiafm

**Comment by segler-alex** [comment]
broken streams get removed automatically.
please just add a new stream with the correct information.

**Comment by isjsg97** [comment]
The problem is that the current url is not that it is broken, it is that the emission is cut from time to time, the new url I put is not cut, then the old one is not going to be removed, because sometimes it works and sometimes it does not
