### ISSUE TITLE
Station Deleted

### ISSUE THREAD

**Issue by josago97** [segler-alex/radiobrowser-api-rust#56]
A few days ago I reported that I unintentionally put a station with the broken url, Issue#55. I did what you told me and I went back up the station with the good link,, well, it turns out that the station with the good link has been deleted and the one containing the broken link is still in the database. I have raised it again to see what happens ....

**Comment by isjsg97** [comment]
And again the new one I uploaded has been deleted.

**Comment by segler-alex** [comment]
could you provide the station link here?

**Comment by josago97** [comment]
stationuuid: e3ea6c86-9909-44e8-af6e-336f25cdf859
current and wrong url: http://icecast-streaming.nice264.com/melodiafmback
correct url: http://icecast-streaming.nice264.com/melodiafm

And I just realized that it is duplicated, there is another with the same link its stationuuid is 54c8a213-7a46-11ea-8a3b-52543be04c81

**Comment by segler-alex** [comment]
i tried it: http://icecast-streaming.nice264.com/melodiafmback is correct and working for me
http://icecast-streaming.nice264.com/melodiafm is NOT working for me, it tells me to authenticate
