### ISSUE TITLE
"301 Moved Permanently" errors from api links, but not old www.links

### ISSUE THREAD

**Issue by deeice** [segler-alex/radiobrowser-api-rust#60]
I get 301 errors from http://api.radio-browser.info/webservice/v2/m3u/url/* requests, but not from requests to the (soon to be expired) http://www.radio-browser.info/webservice/v2/m3u/url/* address.  Maybe I missed a change to the api itself and not just the url?  Otherwise this seems like a problem.

**Comment by segler-alex** [comment]
please read https://api.radio-browser.info/

**Comment by deeice** [comment]
Ah, thanks.  I did miss the api change. Sorry for the bother.
