### ISSUE TITLE
Support geo info in database

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/radiobrowser-api-rust#61]
something like http://radio.garden

**Comment by segler-alex** [comment]
https://github.com/apilayer/freegeoip/

**Comment by vool** [comment]
Would love to see this too, just wondering if lat/lng fields could be added to the DB now, with the locations for individual stations being added later by users or in bulk ?

**Comment by segler-alex** [comment]
added geo-lat and geo-long to use when adding a station manually and as an attribute to be extracted from the stream if it supports it.
