### ISSUE TITLE
Allow filtering based on codec

### ISSUE THREAD

**Issue by csetera** [segler-alex/radiobrowser-api-rust#62]
Maybe I'm missing this somewhere in the API, but I can't find a way to do this.  I'd like to get a list of stations by top votes, but further limit the search results (language, codec, etc).  I've tried a few combination/attempts with GETs and POSTs, but I can't seem to find the ability to do that.  Is it possible?  Otherwise, it would be great to see it added to the feature set.

**Comment by segler-alex** [comment]
have you looked at 
https://de1.api.radio-browser.info/#Advanced_station_search
yet? here you can combine multiple searches into one. 
if this is still not enough please describe exactly what you want to acomplish

**Comment by csetera** [comment]
Funny enough, I was just looking at that.  The part I didn't notice when I first looked at it and wrote this was the "order" parameters.  Is there any way to filter on codec though?  While it looks like most of the streams are MP3, in my current project that is all I can play and it would be nice to be able to restrict to just MP3 as part of the search.

**Comment by segler-alex** [comment]
there is no way to filter on codec yet, i will add it to the wanted features. should not be that bad to add to this call. i will split it into audio codec filter and video codec filter.
but i still want to caution you, after this feature is available, there may be streams that are not mp3 even if they say so (may be this is just a problem for a minority of stream) header information, where i extract this from, is not always correct.

**Comment by csetera** [comment]
I completely understand that you don't control the exact information that is put into the system.  I just appreciate the service at all.  I built a wrapper around Icecast as well, but I really like your voting system.

Should I convert this issue into the codec feature request?  This is not a super high priority, as this is just one of my side projects.

**Comment by segler-alex** [comment]
you don't have to write another issue.  thank you.

**Comment by csetera** [comment]
Thanks!

**Comment by segler-alex** [comment]
no problem, if you want i can link your project on my page, so that more people find it. greetings from vienna
