### ISSUE TITLE
Please remove the Nazi shit

### ISSUE THREAD

**Issue by ZeroDot1** [segler-alex/radiobrowser-api-rust#67]
Beim suchen nach einem Rado Sender habe ich per Zufall einen Hakenkreuzflagge entdeckt, bitte entfernen Sie diese umgehend.

Über den Link können sie die betreffende Station finden.
http://www.radio-browser.info/gui/#!/byname/2Rock

**Comment by segler-alex** [comment]
thank you, it has been removed
