### ISSUE TITLE
Stream link breakage is not detected by stream validator

### ISSUE THREAD

**Issue by kekukui** [segler-alex/radiobrowser-api-rust#68]
The following stream is listed in the database as working (online check = pass)
https://www.radio-browser.info/gui/#!/byname/kiyq

In fact the stream does **not** work because it has changed
(broken stream link in Radio Browser database)
http://24.120.173.242:8002/stream/2/

actual new working stream link:
http://65.156.51.154:8000/stream/2/

**Comment by segler-alex** [comment]
the link currently in the database does work. 
is this still valid?

**Comment by kekukui** [comment]
The original stream link still does not work for me, and is now marked as broken in the database.  Possibly the stream was going online/offline in between test cycles as they migrated to a new server.  I guess this is not a bug and can be closed.  The database only needs to be updated with the new link.

**Comment by kekukui** [comment]
Broken link was cleaned from the database.  New listing created.
