### ISSUE TITLE
Improve tag API performance

### ISSUE THREAD

**Issue by ajsnyde** [segler-alex/radiobrowser-api-rust#7]
When fetching station tags, performance is somewhere around 4-5 seconds (as seen from the front-end), with nearly half a megabyte of data getting sent back. Perhaps gzipping (if that isn't already done) or caching the results of the query would greatly improve the performance. The reason I'm being particular about such a seemingly small issue is because I primarily browse stations by tag.

**Comment by segler-alex** [comment]
i added gzip to www.radio-browser.info/webservice, de1.api.radio-browser.info, de2.api.radio-browser.info, nl1.api.radio-browser.info
thanks for reporting
