### ISSUE TITLE
We should have a pick list for countries.

### ISSUE THREAD

**Issue by rob-dodson** [segler-alex/radiobrowser-api-rust#71]
People can enter anything for a station's country and bad entries are getting into the database. Examples:

```
https://bbc.co.uk
https://youtu.be/gr0EgCcD-v0
jinan
Swiss
Taradell
山东
```

If we had a list of countries we could eliminate this problem, and also settle situations where  countries have multiple names or spellings.

**Comment by segler-alex** [comment]
The country field is outdated. The field countrycode is the one that is used now. the country field will get a calculated field at some point.
If you use the official page to add stations there is a list of countries from restcountries.eu which fills in country and countrycode fields.

how should we handle if someone uses the api directly to add a stream?

**Comment by rob-dodson** [comment]
Ok, I did not understand how it worked, thanks. It might be a better UI to have the pick list, no typing needed to find a country.  The API could require country name or code or else be rejected.

**Comment by segler-alex** [comment]
there are streams without country, which are purely internet based

**Comment by rob-dodson** [comment]
True. Add "Internet" as a country? :-)

**Comment by segler-alex** [comment]
i will make the coutry a calculated field from countrycode and only let legal countrycodes be added

**Comment by rob-dodson** [comment]
Thanks very much.
