### ISSUE TITLE
Allow to have more than one url for a radio station

### ISSUE THREAD

**Issue by Porkepix** [segler-alex/radiobrowser-api-rust#72]
To explain the need, I don't speak here about mirrors, but about how a radio station can offer different quality for its stream (eg. 32kbps, 128kbps and so on), or offer different codecs.

I already saw in the database for example two entries of the same radio station, but calling a different url serving a different codec.

Have a single entry with the different possible url would make more sense to me. It's then up to the client to select the right one (one url could be selected as the default one, though).

**Comment by zartdinov** [comment]
I think it would be right to use two different entities. Something like `Station` and `Stream`.
