### ISSUE TITLE
URL is invalid for a working address (MPEG)

### ISSUE THREAD

**Issue by ukbeast** [segler-alex/radiobrowser-api-rust#76]
I added a radio station http://www.radio-browser.info/gui/#!/history/9f2adf5b-b5e8-4c81-8181-c1981994d2cb
However, I get a warning that url is invalid but, it is able to play through Rhythmbox and vlc. https://kawaii-music.stream.laut.fm/kawaii-music

Shortwave radio also doesn't recognise it.

**Comment by segler-alex** [comment]
i do not see that it is broken, where did you see that?
only streams that are clearly marked as "BROKEN" are invalid. 
it also may take some time for the server to check the stream for meta information.

**Comment by segler-alex** [comment]
the stream has not yet been checked as you can see in the "Last Online Check" value of "never"

**Comment by ukbeast** [comment]
I do apologise on the false report, I can see now that the audio stream now works.
I didn't realise time was required for processing.

**Comment by segler-alex** [comment]
no problem.
