### ISSUE TITLE
Stations /bynamefuzzy

### ISSUE THREAD

**Issue by Suplanus** [segler-alex/radiobrowser-api-rust#78]
Would be great to have fuzzy search built in.

Example:  
The station `ROCK ANTENNE Heavy Metal` would be found if the user searches with the search term `Rock Antenne Metal`.

In the current implementation `/byname` not find the station.

**Comment by segler-alex** [comment]
i like this idea, but i do not have a solution yet. i will do some research how to do this correctly inside the database.

**Comment by NerfBro** [comment]
If you’re using SQL you could try using a SOUNDEX for pattern matching.
