### ISSUE TITLE
Ability to generate a playlist of random stations

### ISSUE THREAD

**Issue by Piciok** [segler-alex/radiobrowser-api-rust#8]
Would it be possible to add a function allowing for generation of random station playlists?

This would help in discovering new stations, especially those with fewer listens and votes.

This could be later added as a feature on both the website and in the Radiodroid app.

**Comment by segler-alex** [comment]
i like this idea, i will implement it
thanks for your idea

**Comment by segler-alex** [comment]
added random order to every station search request
