### ISSUE TITLE
Lower case search query params

### ISSUE THREAD

**Issue by ivandotv** [segler-alex/radiobrowser-api-rust#80]
There are some inconsistencies with how the API is queried:
consider this query:
```https://fr1.api.radio-browser.info/json/stations/search?limit=2&tagList=rap%2cpop%2cjazz```
If you look at the `tagList` it is camel-cased, and the query works ok.
If we change `tagList` to `taglist` the query returns empty results.

also, this works:
```http://fr1.api.radio-browser.info/json/countrycodes/AT``` 
but this doesn't
```http://fr1.api.radio-browser.info/json/countrycodes/at```

I'm trying to create a wrapper library around the API , and this makes it difficult.

Is there any particular reason why are you not lower casing everything on your end?

**Comment by segler-alex** [comment]
the case is now ignored in the next upcoming release for subselects like /json/countries, /json/countrycodes
i will not change the behaviour for tagList at the moment. this is more complicated to change
