### ISSUE TITLE
MetalZone.gr stream URL has changed

### ISSUE THREAD

**Issue by sdroege** [segler-alex/radiobrowser-api-rust#81]
Because of https://github.com/segler-alex/radiobrowser-api-rust/issues/49 it's not possible to edit stations anymore, so I'm reporting the broken URL here instead.

The station at https://www.radio-browser.info/gui/#!/history/9624e616-0601-11e8-ae97-52543be04c81 has a wrong stream URL. It was updated to https://neos.win:48282/stream

**Comment by segler-alex** [comment]
streams cannot be edited currently. there will be an automated way for the stream owner to change their own data.
