### ISSUE TITLE
http connections to api servers get force redirected to https

### ISSUE THREAD

**Issue by kotc** [segler-alex/radiobrowser-api-rust#85]
trying to get any of:
http://de1.api.radio-browser.info/xml/...
http://fr1.api.radio-browser.info/xml/...
http://nl1.api.radio-browser.info/xml/...
results in getting force redirected to https which breaks clients without ssl support, and without adding anything of value. could you disable force redirection to https?

**Comment by segler-alex** [comment]
sorry, but in my opinion, ssl is essential.
security is not optional. of course it is "JUST" a radio index, but also radio indexes could get political in some countries...
