### ISSUE TITLE
Change CORS preflight request to include `User-Agent` header

### ISSUE THREAD

**Issue by ivandotv** [segler-alex/radiobrowser-api-rust#86]
Since the API can be accessed from the front end (browser). The API docs ask us to use `User-Agent` request header, however the CORS preflight request doesn't allow that header. So browser request is blocked.
You can observe the issue in Firefox but not in Chrome, since [Chrome has a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=571722) and it's dropping the header.

**Comment by segler-alex** [comment]
fixed in release 0.7.3
