### ISSUE TITLE
Genres support

### ISSUE THREAD

**Issue by kuba14** [segler-alex/radiobrowser-api-rust#87]
Would it be possible to add support for genres? Currently, all the genres can be found in Tags. However, it is not possible to filter out all the genres. They should be stored separately.

**Comment by segler-alex** [comment]
please explain in more detail what you mean, i think i do not understand your request.
the reason for creating tags is because it is so versatile, you can use it for anything, i liked it for that reason and it also kept my code easier.

**Comment by kuba14** [comment]
Hi, sure, tags are very versatile. But in case you want to get genres of given radio station, you cannot filter them from this relatively large list of tags. Therefore, creating genres would really make the service more professional.
