### ISSUE TITLE
Provide blurhash string for favicon

### ISSUE THREAD

**Issue by onny** [segler-alex/radiobrowser-api-rust#88]
Hey,
I'm currently rewriting my Radio app for Nextcloud which is using your great API.
I noticed that favicons have different loading times in the station list. It depends on their size and sever speeds on the other side.
Would it be possible to return a short blurhash string in the json api response of the favicon? Maybe behind an optional request parameter.
You might already know https://blurha.sh . This is how it would look like for a favicon:

![20201022_22h02m03s_grim](https://user-images.githubusercontent.com/757752/96924373-15ec5780-14a2-11eb-955b-90a237afd9d8.png)

Note the wrong image aspect ratio in the example above. It might look even better ;)
Blurhash images would look great as a placeholder before the actual image is loaded!

Best regards
Jonas

**Comment by segler-alex** [comment]
i understand that this would add the dependency to an external service.

**Comment by onny** [comment]
It is possible to calculate the hashes in rust, see https://github.com/Raincal/blurhash-rs
