### ISSUE TITLE
Data too long for column 'Country' 

### ISSUE THREAD

**Issue by ChernyshovYuriy** [segler-alex/radiobrowser-api-rust#89]
When try to add radio station for United Kingdom and provide country name as
```
United Kingdom of Great Britain and Northern Ireland
```
(according to international standard https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) the server return with the error:
```
{"ok":false,"message":"MySqlError { ERROR 1406 (22001): Data too long for column 'Country' at row 1 }","uuid":""}
```
There is no information in API doc. related to length of the country name.

**Comment by segler-alex** [comment]
country will be ignored in the next release. only countrycode is important.
