### ISSUE TITLE
When searching with offset, report total results count

### ISSUE THREAD

**Issue by onny** [segler-alex/radiobrowser-api-rust#90]
Hey,
in case I limit my search query like this:
https://de1.api.radio-browser.info/json/stations/byname/npr?limit=10
How do I know the total results count without querying all stations?

Best regards,
Jonas

**Comment by erkkki** [comment]
It would be nice to know. 
Most queries you can just load all the results, or just initially load with limit and then all the rest. 
Couple thousand stations is only 250kb.

**Comment by onny** [comment]
Here's an cool example of an API used in the Fyyd podcast database: https://api.fyyd.de/0.2/search/podcast?title=logbuch
This query is searching for podcasts with the title "logbuch" and also shows some meta info about the query.
Docu is here: https://github.com/eazyliving/fyyd-api

**Comment by erkkki** [comment]
Looks like only way to get count is to do another sql query whiteout limit. [stackoverflow](https://stackoverflow.com/a/12887293)

**Comment by segler-alex** [comment]
i am unsure how to handle this, i totally understand the need but i also do not want to double the load on the database ... :(

**Comment by kgarner7** [comment]
As an alternative, would it be possible to also expose a `COUNT` endpoint? In theory, this could still be a doubling of load, but well-behaved clients can store the total count.
