### ISSUE TITLE
Stations by UUID endpoint doesn't work

### ISSUE THREAD

**Issue by ivandotv** [segler-alex/radiobrowser-api-rust#91]
This endpoint always returns empy array.

https://fr1.api.radio-browser.info/json/stations/byuuid?uuids=ae503431-073b-499d-81e9-c32dfa1e32c

https://fr1.api.radio-browser.info/#Search_radio_stations_by_uuid

**Comment by nepodev** [comment]
It Works.
<https://fr1.api.radio-browser.info/json/stations/byuuid?uuids=960e57c5-0601-11e8-ae97-52543be04c81>
you got a typo in uuid.

**Comment by ivandotv** [comment]
Thanks @nepodev 
Yes It appears that somehow I've truncated the last character of the `uuid`
