### ISSUE TITLE
Put data (webradio stream url) in an Git repository

### ISSUE THREAD

**Issue by scls19fr** [segler-alex/radiobrowser-api-rust#95]
Hello,

I looked at radiobrowser code but it seems that data is not in this repository.
I wonder if you have ever considered putting data (essentially webradio stream url with associate metadata) in a Git repository.
So it will be possible to fix errors using pull requests.
A nice idea could be to use a Tabular Datapackage format so it will be very easy to interoperate with this kind of data using several languages.
See https://specs.frictionlessdata.io/tabular-data-package/
An example of such data format can be found at
https://github.com/datasets/country-codes
https://datahub.io/core/country-codes

Kind regards

Related issue
https://github.com/segler-alex/radiobrowser-api-rust/issues/49
Stream url has changed https://github.com/segler-alex/radiobrowser-api-rust/issues/81

**Comment by segler-alex** [comment]
CSV will be in version 0.7.3

**Comment by Lee-Carre** [comment]
For future reference/readers: see Eric Raymond's [The Art of Unix Programming § Design § Textuality](http://www.catb.org/esr/writings/taoup/html/textualitychapter.html).

Since it's a whole chapter (in a non-short book), I'll cite the list of contents for that chapter:
> * [Textuality](http://www.catb.org/esr/writings/taoup/html/textualitychapter.html)
>   * [The Importance of Being Textual](http://www.catb.org/esr/writings/taoup/html/ch05s01.html)
>     * [Case Study: Unix Password File Format](http://www.catb.org/esr/writings/taoup/html/ch05s01.html#id2901332)
>     * [Case Study: .newsrc Format](http://www.catb.org/esr/writings/taoup/html/ch05s01.html#id2901494)
>     * [Case Study: The PNG Graphics File Format](http://www.catb.org/esr/writings/taoup/html/ch05s01.html#png)
>   * [Data File Metaformats](http://www.catb.org/esr/writings/taoup/html/ch05s02.html)
>     * [DSV Style](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2901882)
>     * [RFC 822 Format](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2902039)
>     * [Cookie-Jar Format](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2902164)
>     * [Record-Jar Format](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2906931)
>     * [XML](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2907018)
>     * [Windows INI Format](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2907263)
>     * [Unix Textual File Format Conventions](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2907428)
>     * [The Pros and Cons of File Compression](http://www.catb.org/esr/writings/taoup/html/ch05s02.html#id2907903)
>   * [Application Protocol Design](http://www.catb.org/esr/writings/taoup/html/ch05s03.html)
>     * [Case Study: SMTP, the Simple Mail Transfer Protocol](http://www.catb.org/esr/writings/taoup/html/ch05s03.html#id2908194)
>     * [Case Study: POP3, the Post Office Protocol](http://www.catb.org/esr/writings/taoup/html/ch05s03.html#id2908383)
>     * [Case Study: IMAP, the Internet Message Access Protocol](http://www.catb.org/esr/writings/taoup/html/ch05s03.html#id2908582)
>   * [Application Protocol Metaformats](http://www.catb.org/esr/writings/taoup/html/ch05s04.html)
>     * [The Classical Internet Application Metaprotocol](http://www.catb.org/esr/writings/taoup/html/ch05s04.html#id2908835)
>     * [HTTP as a Universal Application Protocol](http://www.catb.org/esr/writings/taoup/html/ch05s04.html#id2908915)
>     * [BEEP: Blocks Extensible Exchange Protocol](http://www.catb.org/esr/writings/taoup/html/ch05s04.html#id2909217)
>     * [XML-RPC, SOAP, and Jabber](http://www.catb.org/esr/writings/taoup/html/ch05s04.html#id2909294)

The entire book is well-worth reading, for insights into sound software design.

More generally/broadly, the design principles cited near the start of the book are eminently relevant:

> [Basics of the Unix Philosophy](http://www.catb.org/esr/writings/taoup/html/ch01s06.html):
> * Rule of Modularity: Write simple parts connected by clean interfaces.
> * Rule of Clarity: Clarity is better than cleverness.
> * Rule of Composition: Design programs to be connected with other programs.
> * Rule of Separation: Separate policy from mechanism; separate interfaces from engines.
> * Rule of Simplicity: Design for simplicity; add complexity only where you must.
> * Rule of Parsimony: Write a big program only when it is clear by demonstration that nothing else will do.
> * Rule of Transparency: Design for visibility to make inspection and debugging easier.
> * Rule of Robustness: Robustness is the child of transparency and simplicity.
> * Rule of Representation: Fold knowledge into data, so program logic can be stupid and robust.
> * Rule of Least Surprise: In interface design, always do the least surprising thing.
> * Rule of Silence: When a program has nothing surprising to say, it should say nothing.
> * Rule of Repair: Repair what you can — but when you must fail, fail noisily and as soon as possible.
> * Rule of Economy: Programmer time is expensive; conserve it in preference to machine time.
> * Rule of Generation: Avoid hand-hacking; write programs to write programs when you can.
> * Rule of Optimization: Prototype before polishing. Get it working before you optimize it.
> * Rule of Diversity: Distrust all claims for one true way.
> * Rule of Extensibility: Design for the future, because it will be here sooner than you think.

I can easily see how being non-textual is at odds with several of these rules/principles.
