### ISSUE TITLE
multiple bitrates

### ISSUE THREAD

**Issue by okias** [segler-alex/radiobrowser-api-rust#96]
Hello,

first thank you for a great service (I'm using it with [Shortwave](https://gitlab.gnome.org/World/Shortwave)).

Would make sense to add multiple codec format & bitrate to the entry?

1. would be nice to application being able adapt stream speed depending on available bandwidth
2. apps could simply decide which format wants to prefer or use
3. it would make nice fail-over, when one stream fails, it could just iterate to another one

EDIT: it's kinda duplicate, I haven't found any issue related to bitrate, but it seems that #72 is similar request.

**Comment by segler-alex** [comment]
this would need a bigger change in the backend and it would have implications for the structure. I understand the wish completely, but i do not have a good solution yet.
at the moment a single database row is a single stream. this makes handling much easier. and the automatic check that is happening every day needs to be rethought for that.
