### ISSUE TITLE
IS there a way to find a matching stationlogo by searching by station URL?

### ISSUE THREAD

**Issue by donnersm** [segler-alex/radiobrowser-api-rust#99]
Would love to use this service for finding a matching logo to my stations on my internet radio player MSP32 ...Is there a way to search by stationurl?

**Comment by segler-alex** [comment]
there is currently this in the api
https://de1.api.radio-browser.info/#Search_radio_stations_by_url

but it is not the perfect way, it only searches for unresolved urls. you might not find everything, but it is a start.

**Comment by donnersm** [comment]
ok , Ill look into that..looks promissing
